msg="\n\n\#\#\n\#\#\n\#\# This file was generated by a script. Don't edit it.\n\#\#\n\#\#"

# Compiler and flags
CXX = g++
CXXFLAGS = -Wall -g

# 1. Create new targets for your executables
# 2. Modify pt-sim.sh and pt-sim-clock.sh to call appropriate executable
# 3. Include them in the dependencies

all: ptsim-bin ptsim ptsim-clock

# Compile C++ binary
ptsim-bin: main.o page-table.o
	$(CXX) $(CXXFLAGS) -o ptsim-bin main.o page-table.o

main.o: main.cpp page-table.hpp
	$(CXX) $(CXXFLAGS) -c main.cpp

page-table.o: page-table.cpp page-table.hpp
	$(CXX) $(CXXFLAGS) -c page-table.cpp

# Shell script wrappers
ptsim: pt-sim.sh ptsim-bin
	cp pt-sim.sh ptsim
	@echo -e ${msg} >> ptsim

ptsim-clock: pt-sim-clock.sh ptsim-bin
	cp pt-sim-clock.sh ptsim-clock
	@echo -e ${msg} >> ptsim-clock

# Clean target
clean:
	rm -f *.o ptsim-bin ptsim ptsim-clock
